## Github workflow to build a docker image from source

name: Docker Image (Source)

on:
  workflow_dispatch:
  workflow_call:

## Define which docker arch to build for
env:
  docker_platforms: linux/amd64
  docker-org: albu02

concurrency:
  group: docker-image-source-${{ github.head_ref || github.ref || github.run_id }}
  ## Always cancel duplicate jobs
  cancel-in-progress: true

jobs:
  ## Runs anytime `ci.yml` runs or when manually called
  image:
    name: Build Image
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      ## Build a maximum of 2 images concurrently based on matrix.dist
      max-parallel: 2
      matrix:
        dist:
          - debian
    steps:
      ## Setup Docker for the builds
      - name: Docker setup
        uses: BowTiedDevOps/actions/docker@feat/retry-action
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      ## Set docker metatdata
      - name: Docker Metadata ( ${{matrix.dist}} )
        id: docker_metadata
        uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81 #v5.5.1
        with:
          images: |
            ${{env.docker-org}}/${{ github.event.repository.name }}
            ${{env.docker-org}}/stacks-core
          tags: |
            type=raw,value=${{ env.BRANCH_NAME }}
            type=ref,event=pr

      ## Build docker image
      - name: Build and Push ( ${{matrix.dist}} )
        id: docker_build
        uses: docker/build-push-action@4a13e500e55cf31b7a5d59a38ab2040ab0f42f56 # 5.1.0
        with:
          file: ./.github/actions/dockerfiles/Dockerfile.${{matrix.dist}}-source
          platforms: ${{ env.docker_platforms }}
          tags: ${{ steps.docker_metadata.outputs.tags }}
          labels: ${{ steps.docker_metadata.outputs.labels }}
          build-args: |
            REPO=${{ github.repository_owner }}/${{ github.event.repository.name }}
            STACKS_NODE_VERSION=${{ env.GITHUB_SHA_SHORT }}
            GIT_BRANCH=${{ env.GITHUB_REF_SHORT }}
            GIT_COMMIT=${{ env.GITHUB_SHA_SHORT }}
          push: ${{ env.DOCKER_PUSH }}
